// A memorable `adjective-animal` slug for auto-created worktree dirs (e.g. "brisk-otter").
// Replaces the old base36 timestamp suffix, which produced near-indistinguishable names
// like `pilot-mqqezjj2` that were miserable to tell apart in `ls`. ~60×60 ≈ 3.6k combos —
// big enough that collisions are rare, and the caller (createWorktree) re-rolls on the
// off chance a sibling dir already exists.

const ADJECTIVES = [
  "amber",
  "brave",
  "brisk",
  "calm",
  "clever",
  "cobalt",
  "copper",
  "coral",
  "crisp",
  "dapper",
  "deft",
  "eager",
  "fleet",
  "fond",
  "gentle",
  "glad",
  "golden",
  "hardy",
  "hazel",
  "jade",
  "jolly",
  "keen",
  "lively",
  "lucid",
  "lunar",
  "mellow",
  "merry",
  "mild",
  "nimble",
  "noble",
  "peppy",
  "placid",
  "plucky",
  "polar",
  "proud",
  "quick",
  "quiet",
  "rapid",
  "rosy",
  "ruby",
  "rustic",
  "sage",
  "sandy",
  "sleek",
  "snug",
  "solar",
  "spry",
  "stout",
  "sunny",
  "swift",
  "tidy",
  "trusty",
  "vivid",
  "warm",
  "wily",
  "witty",
  "zesty",
];

const ANIMALS = [
  "otter",
  "badger",
  "finch",
  "heron",
  "lemur",
  "marten",
  "ocelot",
  "panda",
  "quail",
  "raven",
  "robin",
  "sable",
  "tapir",
  "vole",
  "walrus",
  "wombat",
  "yak",
  "zebra",
  "bison",
  "crane",
  "dingo",
  "egret",
  "ferret",
  "gecko",
  "gopher",
  "hawk",
  "ibex",
  "jackal",
  "koala",
  "lynx",
  "mole",
  "newt",
  "osprey",
  "puma",
  "rabbit",
  "seal",
  "stoat",
  "toad",
  "viper",
  "weasel",
  "wren",
  "falcon",
  "beaver",
  "mantis",
  "cricket",
  "sparrow",
  "magpie",
  "kestrel",
  "pelican",
  "narwhal",
  "manatee",
  "meerkat",
  "mongoose",
  "possum",
  "raccoon",
  "salmon",
  "turtle",
  "antelope",
  "dolphin",
  "puffin",
];

function pick<T>(arr: readonly T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

/** A memorable `adjective-animal` worktree slug (e.g. "brisk-otter"). */
export function randomWorktreeName(): string {
  return `${pick(ADJECTIVES)}-${pick(ANIMALS)}`;
}
